### ISSUE TITLE
Elastalert plugin not loading due to CSP error on Kibana 7.3.0

### ISSUE THREAD

**Issue by stevengoossensB** [bitsensor/elastalert-kibana-plugin#121]
Since the upgrade to Kibana 7.3.0 and the Elastalert kibana plugin, my browser doesn't load the plugin anymore. I'm using the most recent version of Chrome and am getting the following error in the Chrome debugger. I've tried playing with the newly introduced csp settings in Kibana.yml as a test, but that doesn't change anything.

Any thought on what might be the issue here?

Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (elastalert-kibana-plugin.bundle.js:3)
    at Object.<anonymous> (commons.bundle.js:3)
    at __webpack_require__ (elastalert-kibana-plugin.bundle.js:3)
    at Object.__kbnBundles__.elastalert-kibana-plugin (elastalert-kibana-plugin.bundle.js:14)
    at __webpack_require__ (elastalert-kibana-plugin.bundle.js:3)
    at checkDeferredModules (elastalert-kibana-plugin.bundle.js:3)
    at __kbnBundles__.elastalert-kibana-plugin (elastalert-kibana-plugin.bundle.js:3)
    at elastalert-kibana-plugin.bundle.js:3

**Comment by nsano-rururu** [comment]
@stevengoossensB 

In my environment, I started it with docker-compose with a combination of Kibana 7.3.0 and elastalert-kibana-plugin for Kibana 7.3.0, and confirmed that there is no problem.
Are there still issues with the combination of elastalert-kibana-plugin for Kibana 7.3.0 and Kibana 7.3.0?

```
cd
mkdir work
cd work
mkdir Dockerfiles
mkdir -p es/config
mkdir -p es/data
chmod 777 es/data
mkdir -p kibana/config
mkdir -p elastalert/bin
mkdir -p elastalert/config
mkdir -p elastalert/public/js
mkdir -p elastalert/nginx_config
mkdir -p elastalert/rule_templates
chmod 777 elastalert/rule_templates
mkdir -p elastalert/rules
chmod 777 elastalert/rules
cd elastalert/nginx_config
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/nginx_config/default.conf
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/nginx_config/nginx.conf
cd ../
cd public/js
get https://raw.githubusercontent.com/ServerCentral/praeco/master/public/js/cron-ui.min.js
cd ../
wget https://github.com/ServerCentral/praeco/blob/master/public/favicon.ico
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/public/index.html
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/public/praeco.config.json
cd ../../
```

docker-compose.yml

```
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 180s

  kibana:
    container_name: kibana
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-kibana-730
    image: kibana:7.3.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/plugin:/usr/share/kibana/work
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 200s

  elastalert:
    container_name: elastalert
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.elastalert
    image: elastalert:0.2.1
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
      - ./elastalert/rule_templates:/opt/elastalert/rule_templates
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 200s
```

Dockerfiles/Dockerfile-kibana-730

```
FROM docker.elastic.co/kibana/kibana:7.3.0

USER root

RUN /usr/share/kibana/bin/kibana-plugin install --allow-root https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.3.0.zip

USER kibana
```

Dockerfile.elastalert

```
FROM servercentral/elastalert:latest

USER root

RUN apk update && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

ADD praeco/bin/elastalert-start.sh /usr/local/bin/
ADD praeco/bin/elastic_search_status.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/elastalert-start.sh 

USER node

ENTRYPOINT ["/usr/local/bin/elastalert-start.sh"]
```

es/config/elasticsearch.yml

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

kibana/config/kibana.yml

```
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
# elastalert-kibana-plugin
elastalert-kibana-plugin.serverHost: elastalert
elastalert-kibana-plugin.serverPort: 3030
```
elastalert/bin/elastalert-start.sh

```
#!/bin/bash

set -e

echo "Giving Elasticsearch at $ELASTICSEARCH_URL time to start..."

elastic_search_status.sh

echo "Starting ElastAlert!"
npm start
```

elastalert/bin/elastic_search_status.sh

```
#!/bin/bash

set -e

if [ $# -gt 0 ]; then
  ES_URL="$1"
elif [[ -n $ELASTICSEARCH_URL ]]; then
  ES_URL="$ELASTICSEARCH_URL"
elif [[ -n $ES_HOST ]] && [[ -n $ES_PORT ]]; then
  ES_URL="http://$ES_HOST:$ES_PORT"
else
  ES_URL="http://elasticsearch:9200"
fi

until [[ "$(curl -fsSL "$ES_URL/_cat/health?h=status" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" =~ ^(yellow|green)$ ]]; do
  # printf '+' >&2
  sleep 1
done

echo "Elasticsearch is up and healthy at "$ES_URL"" >&2
```

elastalert/api.config.json

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
```

elastalert/elastalert.yml

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True
```
