### ISSUE TITLE
serverHost and serverPort: Check for spelling errors and ensure that expected plugins are installed.

### ISSUE THREAD

**Issue by trebolcinco** [bitsensor/elastalert-kibana-plugin#132]
I have set the two values in kibana.yml:

elastalert-kibana-plugin.serverHost: 10.0.0.210
elastalert-kibana-plugin.serverPort: 3030

But keep getting this message:

```{"type":"log","@timestamp":"2019-11-12T19:09:59Z","tags":["fatal","root"],"pid":1,"message":"{ Error: \"elastalert-kibana-plugin.serverHost\" and \"elastalert-kibana-plugin.serverPort\" settings were not applied. Check for spelling errors and ensure that expected plugins are installed.\n    at KbnServer.exports.default (/usr/share/kibana/src/server/config/complete.js:88:17) code: 'InvalidConfig', processExitCode: 64 }"}```

The server is reachable on 10.0.0.210:3030 and the plugin is installed:

bash-4.2$ kibana-plugin list
elastalert-kibana-plugin@1.0.3

Not sure what to try next.

**Comment by pedrotino** [comment]
Hey, if you have Kibana in a container the plugin folder is usually not part of a volume, so every time you stop the container the plugins might "disappear"

So if thats the case, you will probably need to set up a volume for that folder
for example:
```
    volumes:
      -type: bind
        source: your other volumes
        ....
        ....
      - type: bind
        source: ./kibana/plugins/
        target: /usr/share/kibana/plugins/
        read_only: false  
```

First remove the kibana.yml entries related to the plugin, so you can restart the container/app with no errors.
Make sure the folder/volume that you set up, will have write permissions for the user Kibana, otherwise you wont be able to re-download and install the plugin.

Install the plugin as usual
 `docker-compose exec -T kibana bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.4.1.zip`

In case you get:

> Plugin installation was unsuccessful due to error "Client request error: getaddrinfo ENOTFOUND github.com github.com:443

Download the file manually and place it in a folder/volume that the container can access.
Ill use the plugin folder for this example.
Install the plugin through Offline method
`docker-compose exec -T kibana bin/kibana-plugin install file:////usr/share/kibana/plugins/elastalert-kibana-plugin-1.1.0-7.4.1.zip`

Re-add the entries to kibana.yml and restart kibana

**Comment by nsano-rururu** [comment]
It is possible to check if the plug-in is installed in the command of docker-comose and install it if it is not included.
There is also a way to create a Kibana Docker image with the plugin installed when creating a Docker image with a Dockerfile.

```
cd
mkdir work
cd work
mkdir -p kibana/plugin
cd kibana/plugin
wget https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.4.1.zip
```

(1) Install the plugin as usual

part of docker-compose.yml

```
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    command: sh -c './bin/kibana-plugin list | grep elastalert-kibana-plugin@1.1.0; result=`echo $$?`; if [ $$result = 1 ]; then  ./bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.4.1.zip && exec /usr/local/bin/kibana-docker; else exec /usr/local/bin/kibana-docker; fi'
    ports:
      - 5601:5601
```

(2) Download the file manually and place it in a folder/volume that the container can access.

part of docker-compose.yml

```
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    command: sh -c './bin/kibana-plugin list | grep elastalert-kibana-plugin@1.1.0; result=`echo $$?`; if [ $$result = 1 ]; then  ./bin/kibana-plugin install file:///usr/share/kibana/work/elastalert-kibana-plugin-1.1.0-7.4.1.zip && exec /usr/local/bin/kibana-docker; else exec /usr/local/bin/kibana-docker; fi'
    ports:
      - 5601:5601
    volumes:
      - ./kibana/plugin:/usr/share/kibana/work
```


(3)create a Kibana Docker image with the plugin installed .

vi Dickerfile

```
FROM docker.elastic.co/kibana/kibana:7.4.1

USER root

RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.4.1.zip --allow-root

USER kibana
```

docker build -t kibana:7.4.1 .

part of docker-compose.yml

```
  kibana:
    image: kibana:7.4.1
    ports:
      - 5601:5601
```
