### ISSUE TITLE
Optimizing and caching browser bundles...

### ISSUE THREAD

**Issue by szgaljic** [bitsensor/elastalert-kibana-plugin#66]
Bitsensor ElastAlert 0.0.14 is running at elastalert:3030.

Kibana 6.4.2 started with this docker-compose file:

```
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    restart: always
    networks:
      - elk
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - .:/apps
    environment:
      - "ELASTICSEARCH_URL: http://elasticsearch"
      - "XPACK_MONITORING_ENABLED: false"
    entrypoint: /apps/docker-entrypoint-es-plugins.sh

networks:
  elk:
    external: true
```

The entrypoint script does this:

```
#!/bin/bash
# setting up prerequisites

kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-6.4.2.zip

exec /docker-entrypoint.sh elasticsearch
```
It just hangs at **Optimizing and caching browser bundles...**

```
kibana]# docker-compose up
Creating kibana_kibana_1 ... done
Attaching to kibana_kibana_1
kibana_1  | Attempting to transfer from https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-6.4.2.zip
kibana_1  | Transferring 20147047 bytes....................
kibana_1  | Transfer complete
kibana_1  | Retrieving metadata from plugin archive
kibana_1  | Extracting plugin archive
kibana_1  | Extraction complete
kibana_1  | Optimizing and caching browser bundles...
```

Been hanging there for an hour.
